name: Build Android APK - RESPAD

on:
  push:
    branches: [ principal ] # Ajustado conforme o botão 'principal' do seu print

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências (NPM)
        run: npm install --legacy-peer-deps

      - name: Configurar Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Dar permissão de execução ao Gradle
        run: chmod +x Android/gradlew

      - name: Gerar APK de Release
        run: |
          cd Android
          ./gradlew assembleRelease

      - name: Salvar APK como Artefato
        uses: actions/upload-artifact@v4
        with:
          name: RESPAD-Mobile-v1.0.0
          # Caminho ajustado para 'Android/aplicativo' conforme sua imagem
          path: Android/aplicativo/build/outputs/apk/release/app-release.apk
